name = "gloat"
# version = "n/a"

target = "javascript"
[javascript]
runtime = "deno"
[javascript.deno]
allow_read = ["gleam.toml", "./src", "./test", "./build"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 1.0.0"
argv = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.3.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
